// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAv8EM8u1vo3-6Rdd_AKqoU_hlld-zVvI',
    appId: '1:101128857078:android:871b61c5c4693e31cc13d7',
    messagingSenderId: '101128857078',
    projectId: 'flutter-chat-app-aed58',
    databaseURL: 'https://flutter-chat-app-aed58-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-chat-app-aed58.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBP-spIatUDCshrkyDKrQauQ06wl0z6_DY',
    appId: '1:101128857078:ios:5bdea095639d7eafcc13d7',
    messagingSenderId: '101128857078',
    projectId: 'flutter-chat-app-aed58',
    databaseURL: 'https://flutter-chat-app-aed58-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-chat-app-aed58.appspot.com',
    iosClientId: '101128857078-01mqp6hikdd3nefobt6ssiktrvkv38c2.apps.googleusercontent.com',
    iosBundleId: 'com.yourcompany.flutterChatApp',
  );

}